language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit -c test/config.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v